apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 100-iommu
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
  kernelArguments:
      - amd_iommu=on
