apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki 
  namespace: openshift-logging 
spec:
  size: 1x.small 
  storage:
    schemas:
    - version: v13
      effectiveDate: "2022-06-01"
    secret:
      name: logging-loki-s3 
      type: s3 
    tls:
      caName: openshift-service-ca.crt
  storageClassName: lvms-vg1
  tenants:
    mode: openshift-logging 
