---
- name: homelab start and stop
  hosts: localhost
  vars:
    power: ""
  vars_files:
    - ./homelab-ocp-build/vars/vars_in_a_vault.yaml
  tasks:

     - name: SuperMicro - Power OFF
       community.general.redfish_command:
         category: Systems
         command: PowerGracefulShutdown
         baseuri: "{{ bmc_address }}"
         username: "{{ bmc_user }}"
         password: "{{ bmc_password }}"
       when: 
         - power == "off"
         - power is defined

     - name: SuperMicro - Power ON
       community.general.redfish_command:
         category: Systems
         command: PowerOn
         baseuri: "{{ bmc_address }}"
         username: "{{ bmc_user }}"
         password: "{{ bmc_password }}"
       when: 
         - power == "on"
         - power is defined
